[tool.black]
line-length = 88
target-version = ["py311"]
skip-string-normalization = true
black . --exclude '(^|/)test_.*\.py$'

[tool.isort]
profile = "black"
line_length = 88
multi_line_output = 3
include_trailing_comma = true
skip_glob = ["test_*.py"]

[tool.mypy]
python_version = "3.11"
strict = true
ignore_missing_imports = true
disallow_untyped_defs = true
check_untyped_defs = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_return_any = true
no_implicit_optional = true
exclude = '(^|/)test_.*\.py$'

[tool.pytest.ini_options]
addopts = "--strict-markers"
testpaths = ["api/tests"]
markers = [
    "happy: tests for happy path scenarios",
    "edge: tests for edge cases"
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
