name: Frontend React CI

on:
  push:
    paths:
      - 'frontend/**'
  pull_request:
    paths:
      - 'frontend/**'

jobs:
  lint-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          cd frontend
          npm ci

      - name: Run ESLint
        run: |
          cd frontend
          npm -g i eslint-cli
          npm install eslint --save-dev
          npm run lint

      - name: Run TypeScript check
        run: |
          cd frontend
          npm -g i typescript
          npm install typescript --save-dev
          npm run typecheck
